version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      NODE_OPTIONS: "--max-old-space-size=8192"
    stdin_open: true

  database:
    build:
      dockerfile: Dockerfile
      context: ./database
    container_name: fall_in_asia_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "3060:3060"
    environment:
      NODE_OPTIONS: "--max-old-space-size=8192"
